config/routes.rb
Rails.application.routes.draw do

  root 'home#index'

  resources :scholarships, :only => [:new, :create, :edit, :update, :show, :destroy]

  get "donatello" => "sessions#login"
  post "login_attempt" => "sessions#login_attempt"
  get "logout" => "sessions#logout"

  get ':action' => 'pages#:action'

end

app/models/scholarship.rb
class Scholarship < ActiveRecord::Base
  extend FriendlyId
  friendly_id :title, use: :slugged
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessor :password

  before_save :encrypt_password
  after_save :clear_password

  def encrypt_password
    if password.present?
      self.salt = BCrypt::Engine.generate_salt
      self.encrypted_password = BCrypt::Engine.hash_secret(password, salt)
    end
  end

  def clear_password
    self.password = nil
  end

  def match_password(password)
    encrypted_password == BCrypt::Engine.hash_secret(password, salt)
  end


  # class method
  def self.authenticate(username, password)
    @user = User.find_by_username(username)

    if @user && @user.match_password(password)
      return @user
    else
      return false
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  protected
  def authenticate_user
    if session[:user_id]
      @current_user = User.find(session[:user_id])
      return true
    else
      redirect_to root_path
      return false
    end
  end

  def save_login_state
    if session[:user_id]
      redirect_to root_path
      return false
    else
      return true
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
    @scholarships = Scholarship.where(major: "S1").order(closing_date: :asc)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def contact
  end
end

app/controllers/scholarships_controller.rb
class ScholarshipsController < ApplicationController
  before_filter :authenticate_user, :except => [:show]

  def new
    @scholarship = Scholarship.new
  end

  def create
    @scholarship = Scholarship.new(scholarship_param)
    @scholarship.save

    redirect_to root_path
  end

  def edit
    @scholarship = Scholarship.friendly.find(params[:id])
  end

  def update
    @scholarship = Scholarship.friendly.find(params[:id])

    if @scholarship.update(scholarship_param)
      redirect_to root_path
    else
      render 'edit'
    end
  end

  def destroy
    @scholarship = Scholarship.friendly.find(params[:id])
    @scholarship.destroy

    redirect_to root_path
  end

  def show
    @scholarship = Scholarship.friendly.find(params[:id])
  end

  private
  def scholarship_param
    params.require(:scholarship).permit(
      :title,
      :description,
      :opening_date,
      :closing_date,
      :category,
      :major
    )
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_filter :save_login_state, :only => [:login, :login_attempt]

  def login
  end

  def login_attempt
    authorized_user = User.authenticate(params[:username], params[:password])

    if authorized_user
      session[:user_id] = authorized_user.id
      redirect_to root_path
    else
      flash[:notice] = "Invalid username or password"
      render "login"
    end
  end

  def logout
    session[:user_id] = nil
    redirect_to root_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def title(page_title)
    content_for :title, page_title.to_s
  end

  def show_deadline(datetime)
    if datetime < (DateTime.now + 1.month) and datetime > DateTime.now
      html = "<span class='alert label'>"
      html += datetime.strftime("%d %B %Y")
      html += "</span>"
    else
      html = datetime.strftime("%d %B %Y")
    end

    return html.html_safe
  end

  def current_user
    return session[:user_id].present?
  end

end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/scholarships_helper.rb
module ScholarshipsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/home/index.html.erb
<%- title "Informasi Beasiswa untuk Pelajar Indonesia" %>

<table class="scholarships">
  <thead>
    <tr>
      <th width="5%"></th>
      <th width="60%">Beasiswa</th>
      <th width="20%">Batas Waktu</th>
      <th width="15%">Kategori</th>
    </tr>
  </thead>

  <tbody>
    <% @scholarships.each do |s| %>
      <tr>
        <td></td>
        <td><%= link_to s.title, scholarship_path(s) %></td>
        <td><%= show_deadline(s.closing_date) %></td>
        <td><%= s.category %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <meta name="description" content="Informasi Beasiswa untuk Pelajar Indonesia" />
    <meta name="keywords" content="daftarbeasiswa.com, beasiswa, S1" />
    <meta name="author" content="daftarbeasiswa.com" />

    <meta property="fb:admins" content="daftarbeasiswa.com" />
    <meta property="og:title" content="daftarbeasiswa.com | <%= content_for?(:title) ? yield(:title) : "daftarbeasiswa.com" %>" />
    <meta property="og:type" content="website" />
    <meta property="og:url" content="http://daftarbeasiswa.com" />
    <meta property="og:site_name" content="daftarbeasiswa.com" />
    <meta property="og:description" content="<%= content_for?(:title) ? yield(:title) : "daftarbeasiswa.com" %>" />
    <meta property="og:image" content="<%= image_path('graduation.jpg') %>" />

    <title>daftarbeasiswa.com | <%= content_for?(:title) ? yield(:title) : "daftarbeasiswa.com" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= stylesheet_link_tag    "http://fonts.googleapis.com/css?family=Lobster" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <div class="row" id="header">
      <div class="small-8 columns">
        <h1 class="site-title"><%= link_to "daftarbeasiswa.com", root_path %></h1>
      </div>

      <div class="small-4 columns site-search">
        <!--
        <div class="row collapse">
          <div class="small-9 columns">
            <input type="text" placeholder="Pencarian" />
          </div>
          <div class="small-3 columns">
            <a href="#" class="button postfix"><i class="fa fa-search"></i></a>
          </div>
        </div>
        -->
        <% if current_user %>
          <ul class="inline-list">
            <li><a href="/scholarships/new">Tambah Data Beasiswa</a></li>
            <li><a href="/logout">Logout</a></li>
          </ul>
        <% end %>
      </div>
    </div>

    <div class="row" id="content">
      <div class="small-12 columns">
        <%= yield %>
      </div>
    </div>

    <div class="row" id="footer">
      <%= link_to "Pertanyaan, Kritik dan Saran", "/contact" %> | daftarbeasiswa.com &mdash; 2014
    </div>

    <%= javascript_include_tag "application" %>
  </body>

  <script>
    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
    (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
    m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

    ga('create', 'UA-58095740-1', 'auto');
    ga('send', 'pageview');

  </script>
</html>

app/views/pages/contact.html.erb
<%- title "Pertanyaan, Kritik, dan Saran" %>

<div class="inner-content">
  <h2>Pertanyaan, Kritik, dan Saran</h2>

  <div class="static-content">
    <p><%= link_to "daftarbeasiswa.com", root_path %> adalah portal informasi beasiswa baik dalam negeri maupun luar negeri untuk pelajar Indonesia khususnya untuk jenjang S1 dan D3.</p>

    <p>Sampaikan pertanyaan, kritik, dan ataupun saran anda mengenai website ini ke: <%= mail_to "daftarbeasiswacom@gmail.com" %></p>
  <div>

</div>

app/views/scholarships/edit.html.erb
<%- title "Edit | " + @scholarship.title %>

<h2>Edit Data Beasiswa</h2>

<%= form_for @scholarship do |f| %>
  <div class="row">
    <div class="small-12 columns">
      <%= f.label :title, "Judul" %>
      <%= f.text_field :title, placeholder: "Contoh: Beasiswa Kuliah S1 Gratis Sampai Lulus dari Pemerintah Indonesia" %>
    </div>
  </div>

  <div class="row">
    <div class="small-12 columns">
      <%= f.label :description, "Deskripsi Beasiswa" %>
      <%= f.text_area :description, rows: 25, id: "text-editor" %>
    </div>
  </div>

  <div class="row">
    <div class="small-12 columns select-date-wrapper">
      <%= f.label :opening_date, "Tanggal Buka Beasiswa" %>
        <%= f.date_select :opening_date, {order: [:day, :month, :year]}, class: "select-date" %>
    </div>
  </div>

  <div class="row">
    <div class="small-12 columns select-date-wrapper">
      <%= f.label :closing_date, "Tanggal Tutup Beasiswa" %>
        <%= f.date_select :closing_date, {order: [:day, :month, :year]}, class: "select-date" %>
    </div>
  </div>

  <div class="row">
    <div class="small-3 columns">
      <%= f.label :category, "Kategori Beasiswa" %>
      <%= f.select "category", [['Luar Negeri' ,'Luar Negeri'], ['Dalam Negeri', 'Dalam Negeri']] %>
    </div>
  </div>

  <div class="row">
    <div class="small-2 columns">
      <%= f.label :major, "Jenjang Beasiswa" %>
      <%= f.select "major", [['S1' ,'S1'], ['S2', 'S2'], ['S3', 'S3']] %>
    </div>
  </div>

  <div class="row">
    <div class="small-2 columns">
    <%= f.submit "Edit Data", class: "button" %>
    </div>
  </div>
<% end %>

app/views/scholarships/new.html.erb
<%- title "Tambah Data Beasiswa" %>

<h2>Tambah Data Beasiswa</h2>

<%= form_for @scholarship do |f| %>
  <div class="row">
    <div class="small-12 columns">
      <%= f.label :title, "Judul" %>
      <%= f.text_field :title, placeholder: "Contoh: Beasiswa Kuliah S1 Gratis Sampai Lulus dari Pemerintah Indonesia" %>
    </div>
  </div>

  <div class="row">
    <div class="small-12 columns">
      <%= f.label :description, "Deskripsi Beasiswa" %>
      <%= f.text_area :description, rows: 25, id: "text-editor" %>
    </div>
  </div>

  <div class="row">
    <div class="small-12 columns select-date-wrapper">
      <%= f.label :opening_date, "Tanggal Buka Beasiswa" %>
        <%= f.date_select :opening_date, {order: [:day, :month, :year]}, class: "select-date" %>
    </div>
  </div>

  <div class="row">
    <div class="small-12 columns select-date-wrapper">
      <%= f.label :closing_date, "Tanggal Tutup Beasiswa" %>
        <%= f.date_select :closing_date, {order: [:day, :month, :year]}, class: "select-date" %>
    </div>
  </div>

  <div class="row">
    <div class="small-3 columns">
      <%= f.label :category, "Kategori Beasiswa" %>
      <%= f.select "category", [['Luar Negeri' ,'Luar Negeri'], ['Dalam Negeri', 'Dalam Negeri']] %>
    </div>
  </div>

  <div class="row">
    <div class="small-2 columns">
      <%= f.label :major, "Jenjang Beasiswa" %>
      <%= f.select "major", [['S1' ,'S1'], ['S2', 'S2'], ['S3', 'S3']] %>
    </div>
  </div>

  <div class="row">
    <div class="small-2 columns">
    <%= f.submit "Tambah Data", class: "button" %>
    </div>
  </div>
<% end %>

app/views/scholarships/show.html.erb
<%- title "" + @scholarship.title %>

<div class="inner-content">
  <h2><%= @scholarship.title %></h2>

  <div class="scholarship-meta">
    <div class="row">
      <div class="small-6 columns">
        <div class="row">
          <div class="small-4 columns">
            <h4>Tanggal Buka</h4>
          </div>

          <div class="small-8 columns">
            <%= @scholarship.opening_date.strftime("%d %B %Y") %>
          </div>
        </div>

        <div class="row">
          <div class="small-4 columns">
            <h4>Batas Waktu</h4>
          </div>

          <div class="small-8 columns">
            <%= show_deadline(@scholarship.closing_date) %>
          </div>
        </div>
      </div>

      <div class="small-6 columns">
        <div class="row">
          <div class="small-4 columns">
            <h4>Kategori</h4>
          </div>

          <div class="small-8 columns">
            <%= @scholarship.category %>
          </div>
        </div>

        <div class="row">
          <div class="small-4 columns">
            <h4>Jenjang</h4>
          </div>

          <div class="small-8 columns">
            <%= @scholarship.major %></h4>
          </div>
        </div>
      </div>
    </div>
  </div>

  <div class="scholarship-description">
    <%= @scholarship.description.html_safe %>
  </div>
  <% if current_user %>
    <ul class="inline-list">
      <li><%= link_to "Edit", edit_scholarship_path(@scholarship) %></li>
      <li><%= link_to 'Hapus', @scholarship, method: :delete, data: {confirm: "Are you sure?"}%></li>
    </ul>
  <% end %>
</div>